targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - --minify
            - --no-source-maps
            - -O3
      sass_builder:
        options:
          outputStyle: compressed
