name: ng_modular_admin_demo
description: Demo for ng_modular_admin
authors:
- Mark E. Haase <mehaase@gmail.com>
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: ^6.0.1
  angular_forms: any
  angular_router: any
  ng_fontawesome: any
  ng_modular_admin: any
dependency_overrides:
  ng_fontawesome:
    path: ../ng_fontawesome
  ng_modular_admin:
    path: ../ng_modular_admin
dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_web_compilers: ^2.16.3
  sass_builder: ^2.1.3

